# Generated by Django 5.2.14 on 2026-05-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareersPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_title', models.CharField(default='Join Our Team', max_length=300)),
                ('hero_subtitle', models.TextField(default='Build the future of AI with us')),
                ('hero_description', models.TextField(default="We're looking for talented individuals who are passionate about AI and innovation. Join our team and help transform businesses with cutting-edge AI solutions.")),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='careers/hero/')),
                ('culture_title', models.CharField(default='Our Culture', max_length=200)),
                ('culture_description', models.TextField(default="At OMNEXA AI, we believe in fostering a culture of innovation, collaboration, and continuous learning. We're committed to creating an inclusive environment where everyone can thrive and contribute to our mission.")),
                ('benefits_title', models.CharField(default='Benefits & Perks', max_length=200)),
                ('benefits_description', models.TextField(default='We offer competitive compensation and a comprehensive benefits package to support our team members.')),
                ('cta_title', models.CharField(default='Ready to Make an Impact?', max_length=200)),
                ('cta_description', models.TextField(default='Browse our open positions and find your next career opportunity.')),
                ('cta_button_text', models.CharField(default='View Open Positions', max_length=100)),
                ('cta_button_link', models.CharField(default='#openings', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Careers Page Content',
                'verbose_name_plural': 'Careers Page Content',
            },
        ),
        migrations.CreateModel(
            name='CompanyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(help_text="Font Awesome icon class, e.g. 'fa-solid fa-heart'", max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Benefit',
                'verbose_name_plural': 'Company Benefits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead / Manager'), ('executive', 'Executive')], default='mid', max_length=20)),
                ('category', models.CharField(choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('ai_ml', 'AI / Machine Learning'), ('data_science', 'Data Science'), ('product', 'Product')], default='engineering', max_length=50)),
                ('location', models.CharField(help_text="e.g., 'Gandhinagar, India' or 'Remote'", max_length=200)),
                ('is_remote', models.BooleanField(default=False, help_text='Is this position remote?')),
                ('description', models.TextField(help_text='Job description')),
                ('responsibilities', models.TextField(help_text='Key responsibilities (one per line)')),
                ('requirements', models.TextField(help_text='Requirements and qualifications (one per line)')),
                ('benefits', models.TextField(blank=True, help_text='Benefits offered (one per line)')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary (optional)', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary (optional)', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='INR', help_text='e.g., INR, USD', max_length=10)),
                ('salary_period', models.CharField(default='annual', help_text='e.g., annual, monthly, hourly', max_length=20)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('application_email', models.EmailField(blank=True, help_text='Email to receive applications (if not using form)', max_length=254)),
                ('application_url', models.URLField(blank=True, help_text='External application URL (if not using form)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False, help_text='Feature this job opening')),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_company', models.CharField(blank=True, max_length=200)),
                ('current_position', models.CharField(blank=True, max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('resume', models.FileField(upload_to='careers/resumes/')),
                ('cover_letter', models.TextField(blank=True, help_text='Cover letter or additional notes')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notice_period', models.CharField(blank=True, help_text="e.g., '30 days', 'Immediate', '2 months'", max_length=100)),
                ('referral_source', models.CharField(blank=True, help_text='How did you hear about this position?', max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='received', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.jobopening')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
