# Generated by Django 5.2.14 on 2026-05-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        # Remove old fields
        migrations.RemoveField(
            model_name='jobapplication',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='expected_salary',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='years_of_experience',
        ),

        # Add new fields
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='category',
            field=models.CharField(blank=True, help_text="Interested category (e.g., AI Developer, ML Engineer, etc.)", max_length=100),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='address',
            field=models.TextField(blank=True, help_text="Candidate's address"),
        ),
    ]
