# Generated by Django 5.2.14 on 2026-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(choices=[('real_estate', 'Real Estate'), ('healthcare', 'Healthcare / Clinics'), ('ecommerce', 'E-commerce'), ('coaches', 'Coaches / Consultants'), ('local_business', 'Local Businesses'), ('startups_saas', 'Startups / SaaS'), ('education', 'Education Institutes')], max_length=50, unique=True)),
                ('icon_class', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('problems', models.TextField(help_text='Bullet-separated list of problems (one per line)')),
                ('solution_overview', models.TextField(help_text='One-paragraph AI solution description')),
                ('what_we_implement', models.TextField(help_text='Bullet list of AI tools/services used (one per line)')),
                ('how_it_works', models.TextField(help_text='5 numbered steps, one per line')),
                ('expected_results', models.TextField(help_text='Bullet list of expected results')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Industry Solution',
                'verbose_name_plural': 'Industry Solutions',
                'ordering': ['order'],
            },
        ),
    ]
