# Generated by Django 5.2.14 on 2026-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('client_type', models.CharField(help_text="e.g., 'Real Estate Developer', 'Healthcare Clinic'", max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.TextField()),
                ('services_used', models.TextField(help_text='Services OMNEXA AI implemented')),
                ('ai_strategy', models.TextField()),
                ('process_timeline', models.TextField(help_text="Timeline description, e.g. 'Week 1–2: Setup, Week 3–4: Launch...'")),
                ('results', models.TextField(help_text="Bold highlighted numbers — e.g. '300% traffic growth in 60 days'")),
                ('before_after_data', models.JSONField(default=list, help_text="List of dicts: [{'metric': 'Traffic', 'before': '1K/mo', 'after': '4K/mo'}]")),
                ('testimonial_quote', models.TextField()),
                ('testimonial_client_name', models.CharField(max_length=200)),
                ('testimonial_client_title', models.CharField(blank=True, max_length=200)),
                ('stat_1_label', models.CharField(blank=True, max_length=100)),
                ('stat_1_value', models.CharField(blank=True, max_length=50)),
                ('stat_2_label', models.CharField(blank=True, max_length=100)),
                ('stat_2_value', models.CharField(blank=True, max_length=50)),
                ('stat_3_label', models.CharField(blank=True, max_length=100)),
                ('stat_3_value', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
