# Generated by Django 5.2.14 on 2026-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(help_text="Font Awesome icon class, e.g. 'fa-solid fa-rocket'", max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature Highlight',
                'verbose_name_plural': 'Feature Highlights',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_title', models.CharField(max_length=300)),
                ('hero_subtitle', models.TextField()),
                ('hero_description', models.TextField()),
                ('hero_primary_button_text', models.CharField(default='Book Free Strategy', max_length=100)),
                ('hero_primary_button_link', models.CharField(default='/contact/', max_length=200)),
                ('hero_secondary_button_text', models.CharField(default='View Services', max_length=100)),
                ('hero_secondary_button_link', models.CharField(default='/services/', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('stat_1_label', models.CharField(default='Clients Served', max_length=100)),
                ('stat_1_value', models.CharField(default='500+', max_length=50)),
                ('stat_2_label', models.CharField(default='Projects Completed', max_length=100)),
                ('stat_2_value', models.CharField(default='1000+', max_length=50)),
                ('stat_3_label', models.CharField(default='Years Experience', max_length=100)),
                ('stat_3_value', models.CharField(default='5+', max_length=50)),
                ('stat_4_label', models.CharField(default='Team Members', max_length=100)),
                ('stat_4_value', models.CharField(default='50+', max_length=50)),
                ('services_section_title', models.CharField(default='Our AI Services', max_length=200)),
                ('services_section_subtitle', models.TextField(default='Transform your business with cutting-edge AI solutions')),
                ('services_button_text', models.CharField(default='View All Services', max_length=100)),
                ('services_button_link', models.CharField(default='/services/', max_length=200)),
                ('solutions_section_title', models.CharField(default='Industry Solutions', max_length=200)),
                ('solutions_section_subtitle', models.TextField(default='Tailored AI solutions for every industry')),
                ('solutions_button_text', models.CharField(default='Explore Solutions', max_length=100)),
                ('solutions_button_link', models.CharField(default='/solutions/', max_length=200)),
                ('case_studies_section_title', models.CharField(default='Success Stories', max_length=200)),
                ('case_studies_section_subtitle', models.TextField(default="See how we've helped businesses grow with AI")),
                ('case_studies_button_text', models.CharField(default='View All Case Studies', max_length=100)),
                ('case_studies_button_link', models.CharField(default='/case-studies/', max_length=200)),
                ('blog_section_title', models.CharField(default='Latest Insights', max_length=200)),
                ('blog_section_subtitle', models.TextField(default='Stay updated with AI trends and best practices')),
                ('blog_button_text', models.CharField(default='Read All Articles', max_length=100)),
                ('blog_button_link', models.CharField(default='/blog/', max_length=200)),
                ('cta_title', models.CharField(default='Ready to Transform Your Business?', max_length=200)),
                ('cta_description', models.TextField(default='Get a free AI strategy consultation and discover how we can help you grow.')),
                ('cta_button_text', models.CharField(default='Get Started', max_length=100)),
                ('cta_button_link', models.CharField(default='/contact/', max_length=200)),
                ('testimonials_section_title', models.CharField(default='What Our Clients Say', max_length=200)),
                ('testimonials_section_subtitle', models.TextField(default='Real results from real businesses')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='partners/logos/')),
                ('website_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('client_title', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
