# Generated by Django 5.2.14 on 2026-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('service', models.CharField(choices=[('aeo', 'AEO (Answer Engine Optimization)'), ('ai-marketing', 'AI Marketing & Automation'), ('ai-software', 'AI Software Development'), ('ai-chatbots', 'AI Chatbots'), ('content-creation', 'Content Creation (AI-generated)'), ('image-video', 'Image & Video Generation'), ('blog-writing', 'Blog Writing'), ('lead-generation', 'Lead Generation'), ('meta-ads', 'Meta Ads'), ('landing-pages', 'Landing Page Optimization'), ('social-media', 'Social Media Marketing')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
