# Generated by Django 5.2.14 on 2026-05-11 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
