# Generated by Django 5.2.14 on 2026-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20260511_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBusinessReviewConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place_name', models.CharField(default='OMNEXA AI', max_length=255)),
                ('place_id', models.CharField(blank=True, help_text='Google Place ID (e.g., ChIJN1t_tQuEmsT1o...)', max_length=255)),
                ('api_key', models.CharField(blank=True, help_text='Google Cloud API Key with Places API enabled', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time reviews were synced from Google', null=True)),
                ('sync_enabled', models.BooleanField(default=False, help_text='Enable automatic fetching of reviews from Google')),
            ],
            options={
                'verbose_name': 'Google Business Review Config',
                'verbose_name_plural': 'Google Business Review Configs',
            },
        ),
        migrations.AddField(
            model_name='testimonial',
            name='google_review_date',
            field=models.DateTimeField(blank=True, help_text='Original Google review publish time', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='google_review_id',
            field=models.CharField(blank=True, help_text='Original Google review ID (used to prevent duplicates)', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='google_star_rating',
            field=models.PositiveIntegerField(default=0, help_text='Original Google star rating (if available)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_from_google',
            field=models.BooleanField(default=False, help_text='If True, this review was fetched from Google Business'),
        ),
    ]
