# Generated by Django 5.2.14 on 2026-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tagline', models.CharField(max_length=300)),
                ('icon_class', models.CharField(help_text="Font Awesome icon class, e.g. 'fa-solid fa-brain'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.TextField(help_text='Problem businesses face')),
                ('ai_solution', models.TextField(help_text='How AI solves it')),
                ('what_we_do', models.TextField(help_text='Specific actions OMNEXA AI takes')),
                ('process', models.TextField(help_text='Step-by-step process (use newlines)')),
                ('result', models.TextField(help_text='What client gets')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
