# Generated by Django 5.2.14 on 2026-05-09 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('category', models.CharField(choices=[('aeo', 'AEO'), ('ai_marketing', 'AI Marketing'), ('ai_tools', 'AI Tools'), ('automation', 'Automation'), ('meta_ads', 'Meta Ads with AI'), ('lead_generation', 'Lead Generation'), ('ai_content', 'AI Content Creation')], default='ai_marketing', max_length=50)),
                ('excerpt', models.TextField(help_text='2-line description shown on blog card', max_length=300)),
                ('content', models.TextField(help_text='Full article content (HTML or Markdown)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/images/')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
