# Generated by Django 5.2.14 on 2026-05-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_title', models.CharField(max_length=300)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('about_us_content', models.TextField(help_text='Main about us section content')),
                ('stats_clients', models.PositiveIntegerField(default=0, help_text='Number of clients served')),
                ('stats_projects', models.PositiveIntegerField(default=0, help_text='Number of projects completed')),
                ('stats_years', models.PositiveIntegerField(default=0, help_text='Years in business')),
                ('stats_team', models.PositiveIntegerField(default=0, help_text='Team members')),
                ('cta_title', models.CharField(blank=True, max_length=200)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_button_text', models.CharField(default='Get Started', max_length=100)),
                ('cta_button_link', models.CharField(default='/contact/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='CompanyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(help_text="e.g., '2024', 'Q1 2024'", max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Milestone',
                'verbose_name_plural': 'Company Milestones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(help_text="Font Awesome icon class, e.g. 'fa-solid fa-lightbulb'", max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(help_text="e.g., 'CEO & Founder', 'AI Engineer'", max_length=200)),
                ('bio', models.TextField(help_text='Short biography')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/images/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
    ]
